--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06/04/2020 21:53:36
-- Server version: 5.5.5-10.1.37-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE alfahelix;

--
-- Drop table `courses`
--
DROP TABLE IF EXISTS courses;

--
-- Drop table `team`
--
DROP TABLE IF EXISTS team;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE alfahelix;

--
-- Create table `users`
--
CREATE TABLE users (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_login VARCHAR(30) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  user_full_name VARCHAR(100) NOT NULL,
  user_email VARCHAR(100) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `team`
--
CREATE TABLE team (
  member_id INT(11) NOT NULL AUTO_INCREMENT,
  member_name VARCHAR(100) NOT NULL,
  member_photo VARCHAR(100) DEFAULT NULL,
  member_description TEXT DEFAULT NULL,
  PRIMARY KEY (member_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `courses`
--
CREATE TABLE courses (
  course_id INT(11) NOT NULL AUTO_INCREMENT,
  course_name VARCHAR(100) NOT NULL,
  course_img VARCHAR(100) DEFAULT NULL,
  course_duration DECIMAL(3, 1) NOT NULL,
  course_description TEXT DEFAULT NULL,
  PRIMARY KEY (course_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'admin', '$2y$10$mjs0xu0h6aeh7ynUVyBryOjwS/pRYrr72xNKPD3/PXkJfGKHQ0r62', 'Udemy', 'admin@domain.com');

-- 
-- Dumping data for table team
--
-- Table alfahelix.team does not contain any data (it is empty)

-- 
-- Dumping data for table courses
--
-- Table alfahelix.courses does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;